### ISSUE TITLE
error: **/src/caffe2-ios/caffe2-ios/tinyYoloPredict.pb: No such file or directory

### ISSUE THREAD

**Issue by zklgame** [KleinYuan/Caffe2-iOS#15]
Hello, when I built this Xcode Project, two errors occured:
1. error: **/Caffe2-iOS-master/src/caffe2-ios/caffe2-ios/tinyYoloPredict.pb: No such file or directory
2. error: **/Caffe2-iOS-master/src/caffe2-ios/caffe2-ios/tinyYoloInit.pb: No such file or directory

How can I fix these errors? Thanks

**Comment by zklgame** [comment]
Just delete these two files help me.

**Comment by KleinYuan** [comment]
@zklgame dohh~~ sorry I gitignore them and forgot to add back since they are too large. Just added and you can simply pull from master/2-0-stable.
