### ISSUE TITLE
Would this work for ios11?

### ISSUE THREAD

**Issue by gsrujana** [KleinYuan/Caffe2-iOS#19]
HI, I am working on some development for ios11. Would Caffe2-iOS work on that platform?

**Comment by KleinYuan** [comment]
@gsrujana Haven't fully tested on iOS 11 yet but whenever the official release is public I will test it out and update in the readme.

**Comment by KleinYuan** [comment]
Looks still working.

**Comment by KleinYuan** [comment]
validated and therefore close
