### ISSUE TITLE
Did you tested the performance of the model? Such as the time cost of the predict step?

### ISSUE THREAD

**Issue by raininglixinyu** [KleinYuan/Caffe2-iOS#8]

**Comment by KleinYuan** [comment]
@raininglixinyu 

So, in the master branch, we use [squeezeNet](https://github.com/DeepScale/SqueezeNet) as an example, which is a compressed small model. If your question is asking the specific performance of this model, please check the gif below:

- [X] iPhone 7 plus
- [x] [DispatchTime Measurement](https://developer.apple.com/reference/dispatch/dispatchtime)
- [X] Elapse of function [classifier](https://github.com/KleinYuan/Caffe2-iOS/blob/master/src/caffe2-ios/caffe2-ios/realTimeDetectorVC.swift#L81)

![squeezenet](https://cloud.githubusercontent.com/assets/8921629/25648240/b70331aa-2f7e-11e7-93ac-13c8bab55aa7.gif)

Also, in the meanwhile, I am trying to add more Caffe2 models and will have a performance chart in readme soon.

**Comment by raininglixinyu** [comment]
@KleinYuan Really thanks for your detailed explanation and it helps a lot. The squeezeNet has two versions(v1.0 & v1.1), which one has been used?

**Comment by KleinYuan** [comment]
@raininglixinyu 
The two .pb files are original from [here](https://github.com/caffe2/models).
So, squeezeNet (v1.0 && v1.1) are `.caffemodel` (which works for Caffe) and those two `.pb` files are for Caffe2 model. It's a good question and TBH, I don't know which specific version they used.

Let me raise this and link in here.

**Comment by raininglixinyu** [comment]
@KleinYuan Thanks!This issue can be closed.

**Comment by KleinYuan** [comment]
@raininglixinyu  check [here](https://github.com/caffe2/models/issues/7#issuecomment-301928047)
